service: RestApi-setup

useDotenv: true

provider:
  name: aws
  deploymentMethod: direct
  region: ${env:REGION, "eu-west-2"}
  stage: ${opt:stage, "dev"}
  runtime: python3.9
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:us-east-1:*:table/*"


plugins:
  - serverless-python-requirements

functions:
  create_order: ${file(./Resources/create_order.yml)}
  list_all_customers: ${file(./Resources/list_all_customers.yml)}
  list_all_menu: ${file(./Resources/list_all_menu.yml)}
  list_all_menu_items: ${file(./Resources/list_all_menu_items.yml)}
  list_all_orders: ${file(./Resources/list_all_orders.yml)}

