name: Deploy APIs

on:
  push:
    branches:
      - master

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          npm install -g serverless
          serverless -v
          sls plugin install -n serverless-python-requirements
          serverless deploy --region eu-west-2 --aws-s3-accelerate --verbose